<FailedTestScreen>
    MDBoxLayout:
    # MDCard:
        orientation: 'vertical'
        # md_bg_color: 'yellow'    
        size_hint: None, None
        size: "300dp", "150dp"
        pos_hint: {'center_x': .5, 'center_y': .8}
        spacing: dp(40)
        padding: 1

        MDLabel:
            text: 'К сожалению вы не прошли тест'
            font_name: 'OpenSans'
            halign: 'center'
            font_size: '18sp'
            bold: True

        MDLabel:
            text:  "Lorem ipsum dolor sit amet, consectetur adipiscing elit, Sed blandit libero volutpat sed cras ornare arcu"
            font_name: 'OpenSans'
            font_size: '14sp'
            pos_hint: {'center_y': .5}

        MDRaisedButton:
            text: 'Попробовать ещё раз'
            size_hint_x: 1
            # on_release: root.register()
            elevation: 0
            font_name: 'fonts/OpenSans/OpenSans-SemiBold.ttf'


